### ISSUE TITLE
Sensors displaying first clamp watts only in web and PVoutput (consumption and generation)

### ISSUE THREAD

**Issue by chicos04** [lalelunet/measureit#10]
Hi,
Running 116 on pi. Been playing for few days and noticed the home page totals not aligning with the clamps monitor screen. Also not uploading to pvoutput (now fixed).

BUT the home page and the pvoutput uploads only have the first clamps watts captured. Running the grabber with "test" shows the data from all 3 clamps on both sensors. IE: sensor 0 = 810W and 1 = 19W

'<msg><src>CC128-v1.51</src><dsb>00037</dsb><time>23:24:49</time><tmpr>23.4</tmpr><sensor>0</sensor><id>00579</id><type>1</type><ch1><watts>00810</watts></ch1><ch2><watts>00044</watts></ch2><ch3><watts>00241</watts></ch3></msg>
<msg><src>CC128-v1.51</src><dsb>00037</dsb><time>23:24:52</time><tmpr>23.4</tmpr><sensor>1</sensor><id>01017</id><type>1</type><ch1><watts>00019</watts></ch1><ch2><watts>00017</watts></ch2><ch3><watts>00000</watts></ch3></msg>'
![image](https://cloud.githubusercontent.com/assets/8343856/3813721/851d5e24-1cb5-11e4-95be-1ba7492fb77e.png)

BTW to get all sensors to be recognised for upload to PVoutput I had to put my system ID in each clamp. I have the API in the Global and the System ID on the sensors as well.

Any ideas?
Cheers
Rich

**Comment by lalelunet** [comment]
Include fix in current code
https://github.com/lalelunet/measureit/commit/f144071d1077e888ca9b8ba33afc8987e79c5d87
