### ISSUE TITLE
Option to Log lost / null values as 0

### ISSUE THREAD

**Issue by 22nra** [lalelunet/measureit#15]
Using Pi ver 117
Feature request
I am working on a battery powered PiR sensor to show when movement is detected. The sensor works well but suffered from limited battery life. I have now modified the sensor to only switch on the Tx when movement is detected. So if the sensor is in sleep mode its basically switched off (Envi displays ---) and only comes alive again when the PiR is triggered. It all works well but Measureit seems to freeze when the sensor goes off. Is it possible to log null values as zeros?
Thanks again for your support and work on MeasureIT.

**Comment by lalelunet** [comment]
I can not figured that out.
Measureit itself does not loose or forget sensors. They will be loaded once on startup.
If you plug off and in a appliance this appliance will be automatically removed from the xml and also automaticaly added again if it is pluged in again. 

After the appliance is back in the xml measureit normaly update the data.

:/
