### ISSUE TITLE
MeasureIt 119 no graph if sensor data > 2 hours old.

### ISSUE THREAD

**Issue by wotid** [lalelunet/measureit#18]
I've tried 119 (not the image, I downloaded the source and edited the files I needed to for my specific file locations etc

It appears that if a sensor has no data for > 2 hours, the graph is gone, so is the arrow at the bottom that allows scrolling back through time.

Regards,
Steve.

MeasureIt 119 no data for at least 2 hours, no graph.
![measureit-119](https://cloud.githubusercontent.com/assets/4969030/12835617/ec290e6e-cc05-11e5-9fef-d14190799fb8.jpg)

MeasureIt 117 or 118? no data for at least 2 hours, empty graph.
![measureit-118](https://cloud.githubusercontent.com/assets/4969030/12835616/ec28dfac-cc05-11e5-9252-6e07690accf7.jpg)

MeasureIt 117 or 118? no data for at least 2 hours but able to scroll back.
![measureit-118-12h](https://cloud.githubusercontent.com/assets/4969030/12835680/6bd23ad2-cc06-11e5-871f-2d8df0810889.jpg)
).

**Comment by lalelunet** [comment]
Hi Steve,

nice to hear from you and yes you are right :)
