### ISSUE TITLE
New stats displays

### ISSUE THREAD

**Issue by lalelunet** [lalelunet/measureit#2]
Original Issue:
https://code.google.com/p/measureit/issues/detail?id=61

Reported by smaucourt, Mar 19, 2014
- ability to compare consumption with the same day last year
- ability to compare consumption with the same day last week
- ability to have consumption of the last month (with possibility to compare it with current month)
- have a tendency to consumption (like google adsense for example)

-- i may help --

**Comment by sylvek** [comment]
hi! nice to read it!
(but i migrated to my own project… http://github.com/sylvek/domotik)
