### ISSUE TITLE
version 119 does not start on rpi 3

### ISSUE THREAD

**Issue by lalelunet** [lalelunet/measureit#20]
Image does not work on Raspberry V3

https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=138163

**Comment by wotid** [comment]
I'm running on an RPi 3 but did a manual install. I had to use the latest Raspian (Jessie). None of my Wheezy images would load. (I also uninstalled systemd so I could run Ramlog too.)

I can't remember / don't know if daemon tools worked with systemd or not as I was interested in getting Ramlog working before I installed MeasureIt and the rest of my monitoring software.

**Comment by lalelunet** [comment]
Daemontools are working if they would be startet with systemd. Uninstalling systemd is not a good idea because of it controls a huge of other tools like logging 

I do not like systemd but I learned to live with it. It is the new stuff and it does not go away :/

I ordered a rpi3 today :)

**Comment by lalelunet** [comment]
Here is a new image with the latest raspian base for testing
https://mega.nz/#!nF9DzbSL!anydV-E2hABtLI08HOMt244XOgthb8ivmFH4NHX2wYA

Andrew and Jakub maybe testing it :D

**Comment by lalelunet** [comment]
Hi Thomas,
 
Good news, the image boots fine and I can access the website too. Well done.
 
I have not tested anything else apart from this quick test. I need to move Envir closer to Raspberry and re-install SBFspot (https://sbfspot.codeplex.com/) on the measureit image. I’ll see how I go for time tonight and let you know.
 
Quick question regarding Pvoutput uploads: can measureit upload the consumption data to two different systems on pvoutput? My second system on pvoutput records only consumption to help me work out electricity cost without PV system. The first system has all data: consumption and PV generation.
Come to think of it I can probably get the same information (cost of electricity if I did not have PV) straight from measureit, correct?
 
Cheers
 
 
Jakub

**Comment by lalelunet** [comment]
Hi Thomas,
 
I managed to get the new image going and uploading to my primary system on pvoutput. Everything seems to work well as far as I can tell. Please let me know if there is any specific testing on RPi 3 that you would like me to do. Thanks again for building the new image.
 
........
 
Thank you
 
Jakub
