### ISSUE TITLE
support EMONCMS.org 

### ISSUE THREAD

**Issue by anilRghatikar** [lalelunet/measureit#26]
Hello can you add support for EMONCMS.org . It is part of open source energy monitor project and allows  data manipulation and storage on various devices including pi / linux / nas or online ( free)

The upload is through a simple Api ( json call)

**Comment by lalelunet** [comment]
Hi, 

currently I did not see a future for measureit so I will not invest time to continue this project.

Please see:
https://github.com/lalelunet/measureit/wiki/The-end-of-the-measureit-project-%3F!

Regards 
Thomas
