### ISSUE TITLE
how set password for access site from remote

### ISSUE THREAD

**Issue by Darioits** [lalelunet/measureit#31]
Hi,
 I just configured my (new) Raspberry PI 3b+ with your last iso image, and after some little adjustment it worksvery fine (nice project with possibility to some improvement)
 How can I set user name and password to my web page, because it's online, and anybody can modify parameters.

Thank you in advance
Dario

**Comment by wotid** [comment]
In the php directory locate the file measureit_functions.php, at the top change
$demo = false;

to 

$demo = true;

Then the settings cannot be changed. (If you need to change them, you'll have to change it back to false make the changes and then back to true again).

Regards,
Steve.

**Comment by Darioits** [comment]
Perfect, many thanks
